-- Add is_ai_generated column to flashcards table
ALTER TABLE flashcards 
ADD COLUMN IF NOT EXISTS is_ai_generated BOOLEAN DEFAULT FALSE;

-- Optional: Add a comment
COMMENT ON COLUMN flashcards.is_ai_generated IS 'Flag to indicate if the flashcard was generated by AI';
